package com.loodeer.dao;

import com.loodeer.dataobject.PromoDO;
import com.loodeer.dataobject.PromoDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PromoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo_info
     *
     * @mbg.generated Wed Dec 19 00:47:47 CST 2018
     */
    long countByExample(PromoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo_info
     *
     * @mbg.generated Wed Dec 19 00:47:47 CST 2018
     */
    int deleteByExample(PromoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo_info
     *
     * @mbg.generated Wed Dec 19 00:47:47 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo_info
     *
     * @mbg.generated Wed Dec 19 00:47:47 CST 2018
     */
    int insert(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo_info
     *
     * @mbg.generated Wed Dec 19 00:47:47 CST 2018
     */
    int insertSelective(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo_info
     *
     * @mbg.generated Wed Dec 19 00:47:47 CST 2018
     */
    List<PromoDO> selectByExample(PromoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo_info
     *
     * @mbg.generated Wed Dec 19 00:47:47 CST 2018
     */
    PromoDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo_info
     *
     * @mbg.generated Wed Dec 19 00:47:47 CST 2018
     */
    int updateByExampleSelective(@Param("record") PromoDO record, @Param("example") PromoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo_info
     *
     * @mbg.generated Wed Dec 19 00:47:47 CST 2018
     */
    int updateByExample(@Param("record") PromoDO record, @Param("example") PromoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo_info
     *
     * @mbg.generated Wed Dec 19 00:47:47 CST 2018
     */
    int updateByPrimaryKeySelective(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo_info
     *
     * @mbg.generated Wed Dec 19 00:47:47 CST 2018
     */
    int updateByPrimaryKey(PromoDO record);
}